# Generated by Django 4.2.27 on 2026-01-12 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='H5PGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('completed', models.BooleanField(default=False)),
                ('xapi_verb', models.CharField(blank=True, max_length=100)),
                ('xapi_statement', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'H5P Grade',
                'verbose_name_plural': 'H5P Grades',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='h5pactivity',
            name='h5p_content_url',
        ),
        migrations.RemoveField(
            model_name='h5pactivity',
            name='resource_link_id',
        ),
        migrations.AlterField(
            model_name='h5pactivity',
            name='h5p_content_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='LTIGrade',
        ),
        migrations.AddField(
            model_name='h5pgrade',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='lti_consumer.h5pactivity'),
        ),
        migrations.AlterUniqueTogether(
            name='h5pgrade',
            unique_together={('activity', 'user_id')},
        ),
    ]
