# Generated by Django 4.2.27 on 2026-01-13 16:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='H5PContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('h5p_content_id', models.CharField(db_index=True, help_text='Content ID from the H5P server', max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('object_id', models.CharField(blank=True, help_text='The ID of the object this H5P content is attached to', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='The model type this H5P content is attached to', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'H5P Content',
                'verbose_name_plural': 'H5P Content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='H5PGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, help_text='User identifier (Django user ID or external)', max_length=255)),
                ('score', models.DecimalField(decimal_places=4, help_text='Normalized score (0.0 to 1.0)', max_digits=5)),
                ('raw_score', models.DecimalField(blank=True, decimal_places=2, help_text='Raw score from H5P', max_digits=10, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum possible score', max_digits=10, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('xapi_verb', models.CharField(blank=True, max_length=100)),
                ('xapi_statement', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='django_h5p.h5pcontent')),
            ],
            options={
                'verbose_name': 'H5P Grade',
                'verbose_name_plural': 'H5P Grades',
                'ordering': ['-updated_at'],
                'unique_together': {('content', 'user_id')},
            },
        ),
        migrations.AddIndex(
            model_name='h5pcontent',
            index=models.Index(fields=['content_type', 'object_id'], name='django_h5p__content_6644ee_idx'),
        ),
    ]
